apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-mq-rest-ci-1
  annotations:
    argocd.argoproj.io/sync-wave: "300"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: mq/environments/ci
    repoURL: https://github.com/gitops-workflow-demo/multi-tenancy-gitops-apps
    targetRevision: ocp47-2021-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
