apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAdTw/u7lh59/iwAPX/UhpHgNgz9WQjVVwdSark28ofNJ1tA06hWAooGTpXP+uiVNW+7mDgHlzn6aRzEiqAMImQb4n3Ho6gsTYn066g1ZnvEcPNGckzfSnOKWKoSqXSGiZRnWewvaUKZfxThRBdxZy1DeerNuO6AT/XRpDwNplTfMEdHrkeureZ3rua81fQScHNHABDZTdtMI6JSrw6VSBtPCtUB7z8LiCpEfUv/Kxvfb/tGxDdy63qA9yJM/w1xdV9WoAK/XAa+QFchjHbigvtYsiAccDJPNSptJCjPN/3Cpht3IOiQjExHArpUrMuJl6SGyvKl5d6hPLOPuY8oZSldZKJ5w8oWHHK8xSYpiS8zdSU2vNy0WFbfo4YTYIoS/EvwehW3UavvJROShZFFjltV9W5UFBxXa6kSAWaWRPjLYXsYrbSws7klOKLDgmoM+IpP3JLqa5KorgL4dDDpqrNvJpS5XoJvGj5MP/gUUCs+zDrYPsn2kzVAmDzY7tARF4UoswKDDyDkME/FjKxtjvqWozKwbAE6SZcQCJzb/qJlF/H/GVQ12O/Mr1ba3nitme1ro/uEEWceMDDh0aovrYmVKj8UtIk933moekYiC6JfPfmVY0BHcvCAXJyg5sK25QXmrSfrIIZ0C7CJCelOJEXktanpfIVQA0zH57RCLNKd3JIIaONtKae7/xa6F+3EE0YfVmASDjBQ0UUk+i2MGTlBIXA381ZDi7e3M9gXH1iZjY8zat1fw==
    ARTIFACTORY_PASSWORD: AgCjSQ7EUOTRzRyQ7BHjCyjiDWAL8pFIPOd551vf6f2N/O0h1y+k05xzaE4i3RG97rBkguX6LAL9j5nz0XZpnZPFGxpCjV1OAlzI5EoEB7MnhQ0A6EuoJTomaUwlwM3P5n94L4ntAd/ojzqfy85KacqP1yQfmwswKhcBvGR1qgsCK7N8rWv9PR1ROyzF3uLElAx3oBUoahGaYChpoXqm1B3uMIdxf1elQXcE0hlzFbaIEXjrZlotfvlUPvv1dAfPyHgRy156dgq5FY4KRMykhgc6V7CidAZ9q9Yyheu25L5f433megG2YRDmCUMKgULSeBCKcKc78EhTTu9DhOxM2ym7MCO2bnLN63/TvggG0COjvTc/5Tg8O8qsF8cJ3vJirteDWzOqJa/b/6PDen5CJ8f84qDDRXN/gEWRqZTUf5c8ZBYEVofLbRUs++HvfyYmtGqHhEpT5d9XKqbb61fj5K6DaKCrF4wPqkC8HJ271eV0m0MyicHrNboYh1RcL0D01a+GEtfDN/VfDLiPSLKf0Sr4faTAEwT7UsFjXNc5uMKk1qGQZLnEIPN4njDSUquq0xxyyOkWkFeu/M0umlE0Ij32LyWthebR0e6o4bGYpxPaqsbsWuM6Bbee+azQGomnO+jCvkwKOlNWQ2QJVXshBWlQoxZi1DuL7GGEmfzR8h1a/215mOAvERZDZydgqJpn0M3D4c946MLs6XtTXFwYcK+RyjxgDg==
    ARTIFACTORY_URL: AgBL8lk82wMMonllijzgF+Pe9M7jESm4YFo1zI3/YCFZW9oyl91cVxKvhVK2vefuoYShzwxr5a2O0KOYIN8a9C4YJ9cypm23mlXDp1QZqJI0G5VzORke/p/OarERCva0C0a4PcFjXn20iEZPvHSOOJyh++Jghbv1Hb/WtMIlTNM1UHQwvT3JVxFgWUI3bJ6LQeAgmxkd0vmEH85o9lM/RN49TLeBJnTH2rSjqcAs753P3TX0B/g/UFQo6MbDQkAgQREioP4VRVFVNlDg5iJqoPgtws7Gs6UAfJEV7ZZj/DiMdCoUyL9YVnqI7TIsXyA4FRtNln6pmk+HfvSRNOrIrNRrQ5JlOk4gL7w+lj5b3Q7lL+AIq32skfK9L5IN7JUiV2DqH/POKMtreceZrDNrh/QnM6KNBInxQNVgigU7/0gGA1x8+Vqf8jNFVv6+tq7kjmdS0LA6lh6trKELLAwYAhkZeyoV7Bn9mF/V2feps2cvuPy0WiB4LPBZ0R/b52A1FPAu3HclKuFYCXp8pMc9kVhYdxAEqwAoTVarnjswajJOloC6gSkoZNhmAPGtahs8QnjJr0dmJPd1RLO5pUM8QyY6s/6J7JOlcU+4T6TtE0IlSAu9KcJcHo0AkQHD/mzKNUKgtHFS1+YOVl+nDzdJf79QsKSWUBfFV1XltXTPSuncynN12Bz0/w3IW57yJZBzQJSZIQsUemHmxbN7HC0yF20kMtvgAnccQJfcQI8gyunKurAgOpToTHJlsg==
    ARTIFACTORY_USER: AgAp8wxDOZRi4Dbl8j0tKD2uLEz9WkuEQ7XW53LTW+Y8tQLbFtViduNFbggzkf+BAgN5kEYCtpUcL2Y3GodviiM6qsdRA2ZSQY9or+Bz7sBJkyt4Vwd+yu6sVNovF2WS05MWKPIR/sk9WPVkOp6wvCh5sChTKSNdbsC+CCp/nbc82uQ2mQqRxCE/uWZgfrbsfFTTjzOSJUDaXTmtfNide3cxhrbnBi1MaYHHJ2cB/Hhs9+xSZoIsFnWozmWs/roIlS4dzvKrZKyRqpHbKJTfJo3pZJP54c9CD7lacEdWRjjDvi3pv6nzmw/cacfWRKnUU/lsR0Ye8MlnBQZfC945VjIoLle0wIT2k2k0iKw1/foltxPU0udf/94oLoU4++iDjnKgvgsqfGhaMURqGYpMK1iQ8EH6P/hYE8pzYxRhDU7OJjdofO/pyOMlr6ed2ZXakU6Msma1JBuamyWLPC/QGvoGTYsyRicUL/DdU3nwFvi+Ais3FX7/3UmEvC5Z8f20yRnZ85SZgu9ocawJFu4ZFPPhmp3/mK+rvAZtAQJ7ZuZzlO+hBT9osshFkWRyvs2twLk8UgJV6RtXn8forF4hac+52dUA1h7kf6u3wDe/lyXALQWyHpWz3EV0urAym83hwf5JMDQn4UdJWLTfdaJF+C1SlZM5ZvxLPFwWxhDbrEC4WPG93U9I/S/9bkc7al8AKuPpTdJZvw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:annotations:
              .: {}
              f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:type: {}
        manager: kubectl-client-side-apply
        operation: Update
        time: "2021-09-13T03:21:34Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

