apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgAKerjZNS0mvwjL2VpXdXgJqKDKvxzaQIxuax/54DD/mhCr5RilxSExumHYgxsM07L7CGWVuju/bYgSyulAj9jnBjTtTCcaVoT0Z/R6cmgSDa29PaOnULupqkG/Q6+Idx76jV+ckFVH1mIIcaXnRSM6eUtrwRZakDJ20dPeqb4Go1K9W/BfLlNJDpUIig9gNMp8HAQA5vdlMBh22MuRd5C8Un5Lk9w6FhhpX7EYrBmdUpiATgpr3AKGLxdyFMjchdBCqIk3G/7XLNCpv3yayXgvDoa2AVNaOPUi+AneIJl4tzBSt8h59teB5XOMfuTO12ucRBC7+Gd7m7QZY5BqGnFGYu7ZjFQOTjmCYnptRndV7csSyh8TSQbLIRE1YDxkHBJaNVe1Q0TaqsO5RGXMB88OvEvW7e5NxOpUOdfXLLFKm1xXgDut2d0ryebgr6EH4Nm8iEP0W8fOiQ39qP+ECuGK8fRuo5nDDefdv6X+q3gt/GjFacFJ4mYqH71UHMTeosLNijrK4kKvuWVR3z/fNnE8nto8yuuD+BpO0nR0ce8Vs+KGMt63/pIE9x5qc8G9UAL+zw7w2ajMLQQwee3YrcjzGb1yEScfERToXGDcIJng6blLjx/0E/yzXXT//Qr5/E/fVTTcfDyKQjxpxxYZJsP0Kkq6TxOE1cmhB6wYdJZN2FGp2i7guRb+8t21bXc7bgwI4gdibBK1shZnjXJlDsap5k6SHGTltr2KaJ4vfrR/rMICvZIC3Q==
    ARTIFACTORY_PASSWORD: AgCX7RHsVi8Tfu1YlXK/xxd+Bfu0SPjTFGgc3jlFD7DQ6TuMOPXB429CUqUe3cKhwyriEKojwaQMQhqdQrQIcjZ/PdUSWQJRTf+DBe672KvbUs5/WMOVoZ/tu6oyXrAp9wTZ/UwsfUyNDFAya1WrGi8Am9e3ZLknrK5w4nr4PbCrFfm8Zm4qqOEQ/1kS/DRCsm8Idlf6dHq/Rn91cE5sJMZcVjKP79uTniKBq6DXwCZrEnrYLwYG7ih334IzxcdQ9s3nLk4eHbh/GHU8J+dEJON0hwyCz3sUyoolIBYFc0VDCEShWw9fK88sJW60OCkPRVUt+Po9wrnxL5bDd1qxJyooEVE0gvtF8WihsmVjDUuoyPjmRSPqZVhNrZVLipOMwg6jMG9MY33SdKeQgWHgRFTTeRm1fI68JANiXejxERCEoQzzpxZs/5GeKC7sYKZO9ARWanQNfVwQHCbYFcTN/b0l4VNNhjXAqNy2qu6GBDjrlXZq9KT1h7C0Zj9W3NT2qlQ5KXnJTqFyaRd6G/Adf2goPH8c2gt892jNovXppg4D3JV2yZE7E+KGd9vYqCWRmAXf9BhW6EDWLg7M09LcDzoaLgJeQZvnx3aT3zhwDK3zMysJrye9jqGYSPecevh+CzLxHNhoGKIcm73eL1XrzZgjctk9RFfsiWkLvbyZMgd7NqghmkF6m8OAu/YVqF5Hpl8fa1ssp3Ikv/yOChkF2m0O6w658A==
    ARTIFACTORY_URL: AgA3SVG/IGhom5379Mm+3C+KDMBKP5hRFP5KDKUno35HYlqSPyun2kpQBmFMGQe+zy4ipkltNi1t1sCt3oHI+ySBohcyg+dOmJDTlyQgGFcJVZx33ukD3Na0ypaSjs3qv4QFTnhzGqa/XZm2kOdzEIQQmBdt5wuRo1XPfTbiomT/JMN7gqvvh2QoJk5jgapXuze1lx8jGft5jpgU/iwcSUG6oze2snX6Pstzv5Q9HwqI8KJJ0bDzD6zdn6nNx74vbol0IXSHGeolxnJhJKr/L0gqiIlhI99V3DTOZ2/V2LaQyVpArPRcpU4/KxGHj8mCERtJO+itLPj6uxcwx5R5PnljnuMZY4KGiWZdApNnZB8zLcTFJoEmJQeVhAP+/x6Pv05SSDf0kOYYfrEMuDwaDZ2OC6NDU9YrmHGvf/vtYgmuKrkVZFv70/BXlA4yZJQklUKQYtdOefEXvUlv7+FWVaENGlQ8ciXsC3Rp0eZ+4fleFyA785pKEgUNciME0ftFGFR8EXxzZR925M96tq0kDMZRL7HEJB10XUx91uxWKqIFx3bk+sjt2wha/Eqh9rjT1cD/e7QP6JIPOSiWo8hFDyqq9e9saYKIBkTQuMvQnqXaFjSoIowBbF+JFIR1OouLxynOxSnpz2XSYqWC+WFxdKVsQ7BRDS35vAoVJL1CI9hNhToGK03ID3zBZYipK7/s3XfxfdVFX+7xpIoXobVl8y0/Oxs1wAEHtb2/iKP25IqYa7sSy+VQ++d4uA==
    ARTIFACTORY_USER: AgCE7GwE6pzqgC5ZxV2ubD85doxErXYqyCujLbMS4oY2D8Lv6foa6+vm/gKlyudGiDXLFl9AwsjLw08B5Iqc12yO/5N9PyRazDNEfwwIM6XdaZUUAQOvRTvlM4DCK/rGysOQ1GxOheth9ai3Cc1rq8ZGFZ5KQoxAvZ5VRAtoQr/rjz5rUppxldN1TOUh04dJbKel2Qj2EFDi9fVMLS8Gl/rFI3EdQwoUoaAAoUuU65AT/uomrmblD1s8fF0oVj/lo9c+4g3ovgFuztjJbeQwS2WdEDFgfj6okWqcjkS1UyU27f3fhcjgSN9EMtA9HT+QMcD9x4RqI5NPOeJEeM94CV+ZSfJiM8EzGm0i1vdVZ8bAYB9elVDj10jXdE4Zu5DOagim7WCVAQpEwNEX9EJKgv7vIoWUsuCHaGKGBBLAXg/Yl4hfyQuthnZIwFjDpLTZ1Yrxe1fdm/x8iOk0UVWNwkQ6JtOvtL1rDOe/b6kqqdgmSqEuu3g2Fuqi+nNVYVQ540E7DDG5xF3XBWcf1G2xfURRuMzBhPEqp85T+dz/KyeoOp4Hwuln1ZCZ0sXUlbu03DLpoLIRNBc+W42KX3Mq4HNZWS3AV1QOxsNyGg7ZdlwBTkTq4anDHc1z7WeyYSfbTQeKEMJOI/lLKHU9VQsfwvbWJe8mDvmuokCYdelcjD5bzUyj/Tj+Gn+DOWmH/CrfckcZMcdwYA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:annotations:
              .: {}
              f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:type: {}
        manager: kubectl-client-side-apply
        operation: Update
        time: "2021-09-13T03:21:34Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

