apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgBbefORjCofi9/ceswfB2zVF7jpZdey3+wYQu+mz2LuOZEB+ht2XfnAUmU5TdCm7C4SebY1IBGZ7I62PGGYVES8oQyk2UqtBqmqIGRQjYc4v8qgLOmOK+VE3uQ/sjftqtb6seDWmMn6saGMwEplXgl82tTW7nAzKaBwabBM+h2Cn4H2okikpRl0EOa+nLzAGVxLIuX/IDognlrRBrpzDoiYSpC6HFSJ09HfoSOvENiWiIgd8bA/ZgNov6EfiO54m9E/XG5BKHXG96rrPE/taVJGEiLjSvg7h18Gtp29G3yhaIlminO0tiIqkLvZtx1otbaybti7y8WfeYcdfTkVHYO1div6lgJ0xzWQsdBCnwxwWmQlKK2VOcPYRC98wapOvP0NOXBkYy8Y9YM3LbZXNB0Se3zH1M2ZOtra0xkX0UKG9FeWlgBcBBV29tA5x+xFLU3R7W06IDKQnCxv0nPLK+o2qlwQj8jqVzNAAaN3JV4qhP6aS8/fHimNLpjjVpRmmUgcE8fBB9Bl5N3z+D8+YQ0w2sbcMC/CAvc7UiGVwucZ5ywofLTffeX/ae2iTgjqG0fgj+S9rrC7098DK4QJmG8p1bCi9+AGQ0nP1wvnqB/aqk/naREwy1j5Z/E+Fjn1lrb848fEiP4dRrK/Q/EqY25eJun50pvlfIPq00pDTnZmWNIQKQDdKsrgiHQuIda526btsWVAEgpMyFxpFvn57/XcDuISLkoeX++mwzk/wQFzb1wlWTjrsA==
    ARTIFACTORY_PASSWORD: AgABApgEnX4qSLPZixhasVi3zkT/XuoPzh9eK4PNmdtBDv/6earzNkfWOdZETfKyciEpaZM2m1Jawa0simGohrtvNdEioug9J7hkkvDqJuGXyQiqJjAxWF/pB7iGjh9Ws2Z+XL0zZEyU1hfz9gvImddxt8EHOX8AsCjF4KZ3SG1LPSRe2rNnFSbpe4kBR7DQVszeEkzXcEhb3pYJqyoFd3IRVSIAX5sRnhzfVRZRqsfO0IsAQ1hal9XABVlsW54+9SYjSPFTW/pean08K5UTbvJhiLISgNzUYhmkmTKrRtyzw2HNrT8108gsL+WVfS6tPKZYsj+aCf+1mJJJ4QegfG+iJkzeb/sGZ+OorjQZy0r59qeLptDXemiuTg6/bbsR4w7PASABWO4RuYXPN1K+ssCIeldocAeSIqBbPVy4nBZ2W9KTprMyS2t5yZjvsSytuhE/tbbM6S1OkIHidVIJ2ZfEwX0HRkmaYGLh4geFoZjky4E0nTYdy+6TWgFqwp7NpzS5hlKtEMhpvNa4GMH0vc56SpupY8C4y+4zx+ZmwzBkpxOtNwX6raTDcuCVMPd4N+vyOQhj4Ay6A7oMsWeKa8sjAdHjMt08ClJa039iKlwnY9wOuVRaKuXe/0rTeqfEbvqEZ07a+KyYHRAK1XtArLueBOG4rGEIUSXxhbQFSyDq/Z1uUpyRm81KewQ7mBkrl3m9l1HIsHPugM3HQXJYpzXYOXbKlw==
    ARTIFACTORY_URL: AgB8EhTO4lp6CjJ5vcOP7jYG17R62/qilMd5kw7v5sXtiJjYH8SJ5wlPieNjD+En2SmTcJ6zUZ7GkLVm7cTpx+Hiyp6iJXCxW9wB4fcdM0batOVPTmsJcnZ8lZMtxnv9R8EGTSAq8tR0an2u5gb3oExJyBs1K4Mn1yq2TM5d6A2Ywj2WKmRGPnk+7EjO67sEFQgyTyDo1X5hfrgWfIJccyHYFODv0iMT5NZLhl/5M41eg5mN/WzDdm/aCObumy/MiWpNM125UkmcB42RCFmaAAl2xU2n+5I9UiogD98K2SFjfQUkoNQcFpxWyPfgHEhJ3uALbnVvxmmPiJbgGX/5xd0bCsyihBZvcKzINtoqCFPANZSvjFOXrs7NX9GUGo2hn+J6D27yHTHA0vQsqwl1LP+nl5kcbu6JyVdrUEvGPCNRHlHub7KGZyZ23LtCCjQeY8CTS+J4QMHm9fDRfpgq6mIv6PU53exWCGkp+6a/eZhR7CPQftEQo45k9BKWLqr/RXp/HGHHt5MQlKibwpL0gFeS8zYd//qWGuD9dm2rKEAaAXn4TUkKCbN8IaqLYuUoH1AcfA9H/WBemjqP4pj81ElkemRYyC/llcCC+jWJ5f0GOBw2G0a3dNLGr/CdTsw1GhtuHY4QwcVxpSpL7Z53VrhWojXPcyeu4mT1CBxTbh8dH+ddp8iLGqbm/d0BE5U20j88ah4LBh7bFjHm3LZdaA2OoTD+3Cp59Wev1UzWBboD63QrrGLPmm0qSg==
    ARTIFACTORY_USER: AgBUtmS7AgRS2724/dAEQnjco/zTpctEHKZBlvH5CSs3ob5RORQ06BQnZO9paaKdD+LEzjna+aqr07MbZ+2Yt0YbSXZNHScF4sU1dKachppu1p5aJXdLAISVangNFWFNz/NQlMTFcTnneZoIN3fjb1zD63Zd/kuRB+tzbEzA3g2JdQdo4bwWPYRGdUlkICz+1cQtBh82m3ZCV8J2BPeg11I4qXzkd3yy6l+4/3Dv2cQjXmTKHrIDJKROcI/4kSjXTeGPV4YlZCBGS27jwnK2+rJguCkvKAzqqg1oQGpRV7zIsE2GQgHFhgtW0JSVU11J6V7/fEN6wWqU0q0ptSj8rj5d1TfEp1+4pZv8A826KCBCGf6CVTnqm4Cb9bDNbWjuxuCXIgif7MU20NGx5pbqVLnr24319y8A62GCiW+OqqZKBLS5ikLHn1GiZw5I2UT7PVd4kvJM4qcBqIrVhawvgpPPSI/cmlG8bcVEh01h08CSM0ddT/lSySpzyTKNOjf4WUaWUgoLEC7IqKT8wC89EHZjIGK4eCVAknMm0DW0DE/ict34LBMgSsHH+avI8tsCRlSWwMlN5w6KhKR6p8Ir6xeD2xrWdDelhdtvLg33GwHf9hS2+Z9rEot/ce/ppg5AmnwMlEV3ZMwR+KnZWesIzRGVt2DYzPNO9g4S7z2jAMTv0EDb2fjXHHSbV5UCtNIRYJPgKPeFng==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:metadata:
            f:annotations:
              .: {}
              f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:type: {}
        manager: kubectl-client-side-apply
        operation: Update
        time: "2021-09-13T03:21:34Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

