apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBswCmMKz/HBfCeopyKO6nDRHzs1+uuga9sV46NI7OLzhPrF1qv6eSM6dT38auZGIPGo5S0etydGPLkDK+N2CVcImkrWJ1WrgE6fU1Fq5eoyDQLpsJ1z3pA95LLrOEGuOR5pxWKekvxfSoaJ1MjxTgz/DRZiXVyD/Qr71v4Lb4Wqe91xZosjJt5t645GHL8b+dB4nsq1aBUvNjmRddyvjLB9lpaJ8pIWl7tNyRjo0LF9uNhEl1o8G63+xbHQDHC3qacd+pIdyUOWb/htjYJMsvNpHd0kzchWlkEGJ0BC2RHcW7GRA0kEa9WAv+kxjwziZUTCjCqiYd2wx+QF5O5TSuLm8hikYDlLSvfUa7PfD8nItA5nWDd100S74WECCfMRbrIkqCxMVfybx58qJf+IY5q0r+v2Qc8lVCm03gFiNSfsR++ymVWSfeQJ9AiNoHIZ6csRiyTs+ps7ClBqmfbywF/IDfWLIWQmSOMikR+DTOeDass6Jpe9NjdFg3l+6aIK0Pf5pKOdWNChh2xtY62/dJzTD+yYkT6NdyVjjTMo3duuQZxEMnH4iMQ9UqRSnPeWFY5q/jtUrc9z0WjI4MrCD5t0SKXtg7+6USj/cS0uaQzq+aXaDFe1dHMzoHojD7M2CvVR3qqOM9M+5T0UaZjahPBjENJ3zuQuG7KQburmrnhKugHIwJdV5ncwrjFwUqqviTfjBFC9i5D4DIZDtyNXen6n/lQZwKum3QvNOyhkR7+a+rK5sF83PBR
    username: AgBfmSMiTXbcgkUBeC7oYjRIX6oYnSuuaPwlum44kq8uGe+VxEEcukSI6mhvsgLXA40zA6XqwuimOxmYqfP7bJCHpPfpij7Tq5WY87ppte29lJEMlqNTnVFDc88rUDfDN3skdltdytpNNnWxsaeWhN88+OrTMaDmKeRdGLutXysolayZBye4uOPSSKLiD7GMedBLkTLNaqlhbl/z3k+RgaacOYfHpUr42ZmlrbmiqlpVGZ9lLzbv04/9VceQRo+aOJyb6R60tUQTWKynHdXpFGHaxrfVpupIkZUejn8rOEKskEQipdfBXp6a76oImrwZoakaoikXyxVf6k3xJf/CUtKvNQptxqsWvSGtD17PFzjhOVEXMd0YZg6gCQrLpssCohe1vRcR2dJBhdZnRZEE5nYQ3nCoTxj/34wHCfsEBp7Re7UrEtK9ycCtiEmGQlpHf+fwH/Y+oll5AijusR3qfeyAjYnyASIPq3wRKiKS82DhKV+x39mIActidYPVmmYSOXT/0ivY7ByZgkHBd0Zrp/Ij7yRnnFDdAw5UZaFRS6B6J+XLkTAMWOyq7OxamqrCVeyOKGXD1X6isV3vE6Aw9JVv4DiTmt0jzA0v+x/0ZcBa0wDROqOaAOXeyUMlN8qNXCrEb4EWYb3WqkFKtUe7i9xHsXCk4X2MeEnMad3MAGEUMZjN0patcDZm6ZpsStYBrSbdu6vqEHOk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

