apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgBXXJM5W+BeqqSCWQmpaC4mhHfgq8/ij0+YvfmLAH0huUftRmO3GBYdw2i2pMxcp6iXWSSfrD44Kp38CsANsZn2SnRN07DBms9HluGHvyQI+OPmFd//AOBeb73V9G2qd22ly/niAfPfoUvr83fKIgkxb4exTydGbRDr/lA6V9A/Into8CuubF8PEDxvH371LfW1p0y0HwXkCU6nT8d/gqJxC/Ox1qfBEdSuAkr2zsrMXY2KaBdutLp8CSuXz06PRZbbUqz5gNpHquDxeKALnVIPfbxax6nSPXULIQxcbReC25gfAHqlT28cH6yR6HkyrM4sToW73KQctgO9bKTLmldIeR1HZRtVB6MRUR3BRntFlbCXoN25sNoIO39VcTbcmFxpl9nylyOHUnPDL0y5u2l24DAS/54FRjaP86FuLzEnBl15UZ9Co2bb6s6d+bLLYbXptUY2nh9Pdff+mCV2tPFqijsLYjxFkPMAMoRbYOQ1jECMe/beCbLdHL8+Loi4+o1/OVZUckUDq3dPbVdqz/S+XJ9bsHlm4/ENL8kUB6hNtbcC/78mp9JHYYJPIJaqvbA4SPPsILCpfd7UVWIB6Dxwqtx5+N9AiHDTODewbRXTMAdId5m8d4+sYY/jMreyYLqbvO44Y4CYVlF0DoEim9vfIVRtYHdcNXi2WasuDX9F8jJ+PuXvXCetw5iD1+cKxjNSsqwpsvigIBMLF6cW+Oy1Hj1y+ceCxVlYbFJRBM8fwtIK0/MjqAtg
    username: AgA1HJovHoQIHQY9K1VV1gGGyRHs86386hgDZF3OabE5O3kkhGCpG0eQO729xgHNOkARGlJTYsd1wEX8IzYbDgcevIInhXBb7c3tx0cKvs++Fc4Tq00zFCWgKCvJK/wFriVBiX3JDq49BQh1EHRp2R/2rb44sLDikgvL2b09D6E3P8dZ3pMw8ov/Gqjz09gRyTocaj2psZbbc22hX5KZJZ+3U1jujPlIXH/SQwhQJP2zgP8MxRRzCRsNa3Z7rvDfc2WTEGaSUr099AmGvoby6bHTVyv3Pa3YvIsjwEAtfOEq5P5XsypLgvpVQK8lTticJcH/raGkAZ6MfFvH6dUD5s2HBnR8amA17BnFxeUDxIgrO/qFQ7NTUswet9CYyVWvrQLJdIZIhspdMZJQxLX6kE8NxNH5p8LCJIBmCkdw8wN4Z3Uz2NnucY82m2oJFp2XpIlpSHJ1/XWGSoMPda8yhHU0tmmtmckAI5MM7CusVTO5swNcpI7jJXdHo0vmjAkV7WciXibBMhTd/G5cU3BSO059vAvH7MHSRTgFMTEBCFi0YBKxsyrmc4pFgnEIyIW3VkXPWnxyl7EqcuNClsCpAp9Tw16MF2zU6LOiFo+jZQqsYNp97DB1v86ANi8CM2Tgee0Zv7pcoBfwTz77ZTSUU2R5AwZiBKK/mJM/6dYPkBciIgJUeY0We/T2CuSjwnamrirKv42QmNOC
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

