apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgA90AHIAki2HtlrgOLKwT2j5g+drfQCxU+iFpq8BYmpx04CaYg36Y2zjy33zUKM+SGkHRJQxZNxv8XRD+dqxXdMDAIOB5OqP4U8iVmy6STabTvuBEzMlqp07bIN6zZFKrE5YYF0hj/C8gApiGoqpsTQAtsDCFV8+4FEdefq7coEAxeDeRfWIYgtWYuz0iyYnGHceuRryCLqjYiNY7CSc2z5sFLk0jk7C2BqwpkqKWq55AQypWLlpiogv9JsNdeXrLMBuuGY3gkxrFHghYhvSKwcuhY/ppeN0Q5qp0wgHlfBr1qn9uLSHWo0c+ijA/rcc4rFDPsaOEMden5IJk7DbhRdQ5EG+K0nutBQhieakUObZ2GxNo9A/z31FRpoQd60nBlVuTgSSFujNPEMGWnUrsXdYWKk6BfAGNMG+nf90MSxuR7ZG6EMcvQvK4ra86l4ERkn3/ZMMG7H8tfk0NCXT2S3jPgObDU+mWQUxeIFwbe3hPQP6NXryxwyU888QpD5ebJSraYmfCiUrTk5QQ5N4U2BO3U2rLmBd+BF1qQnymWgB+TIByNUdsI2VQxp9SVSHcXk9ciDnc4j9cGjGEYYYKw2dK1EWfW3H+66lZFWwyA2hrvLxP+G5E7INSWXMDprq6YtNjpYtSU/4uPGKMFCPylMY+bzHmQJEPULTbinxS1RvtRz3VYACxz/S7Zc8sRWndoVxi3LVTm447loMZew0reZJrnGFDwju9btRkgIQ2P3SxM5TVtzDRTu
    username: AgBANYKpeEsE/uCtnynmmW3PXSdjtIqAHKO61OpURuzMzdGWPE2fQVvQHxgUXcyUhuA3PxnIlRSKWfnegDSXKtTJZQvFeRHKVWKi7/7Z+Gl0sP17QGicOzb34dxdeU0D42fetODo228P9b6xBtRGaVBn6oDpia6xVejisMWDPrx40OEPkw9GxtjbRI1236gAt75QtZMso30iGgZCMkejksukUqzQJ7ZuxTfgLcFkCS1iCP2FL4eHsVpyYAcC8WC2dte1Mpjz9lAi8ncsvnkRAgiiDFY9yArxmbh7WKzZV1UaORxgu+lUvFPFHPnnA4fbwp/WUtRwFA1rT2PCr0qYMaz0j9mv4I/Jj1Um9gek9fNRW0aZA1LkH1Ht39BNq5M2xtQJFDfYDxrgZp65jFWxKpw2nHavu4Udi28Hs+qeIc/KOTd7R7PraGweKB4EbP9tHA9yB8pykb7ABA/cTNrfZkjZjLO8Vsi2lXLWLO6u7APSzKloHdb2PFFzQ1VHdoXHoeCGdzKiUN65p9G1PNkZYULOjMjNO7V+jcMbh2/o39aALeKdAcsHqAGOFgQ+UwlW1qNY65w7eJ213v2d7FeR9B8p6D39h5Lb+BxN8ZfXCn2xcCq6z+GSX/pOtC/kLXsjaX7ZaZxlvRfamuHOSuLPBSoWfFVKvTT1tgh2iLTzvnK70Sz7japRVc4AFJki2KzG7ojIehOUwZ/g
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

