apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgAz8QlLjAySy2yyv1kpt+tc6LMFAi9NvpdVVBwZk1+XwKpAz5zgwg8h5LeQncs0g3W7LKCEjgyt2sM46ynmIbQKASwTYqXBFK3GEHhqlI5/EJgn1Yjtoj0573jHJ/wUx3pkuBuV0HgWZyWXb5TGCPpLZEu6uX0xJ4P8WuQeWPeSsHyAJP90xcE/hVfMBBrAIHSsrTWrCbToELNinQIxjHaokiZh6fR51ez/u4WTkBtJg53fysCoGPsqVdgh1koNJeIFTv3gWNImMB3hZGMfnF7O5L9WGHOtR9jkQSltaauniNkTNKoxGz3EgbjIzcFgoSn3pT7KaGypgTvZp7N9sl6qIkNtDYnAdin1wFPObH5D3j3ZyesB3kCs1SwaxYTJsum1PLxaHgPfm7MbQS53rl6jIdU9rMSdd+KkK7feljDzECVtbhKU7az9+5w7kwhYWvjDzrOjibdXHFfUipyZ3gGcHeZIMd1rp1SbqFVXPtTsQkR+kN3jx/eQGNStWaePcM6uZAiqJmjpvQdyyDijmy18D+6rYvdt93WefQ6W0bRprdREIQJidxdlmvJMwtW3Uie8ci3DXi7g9IqImPI8JctyyWzPYjGXnIUlaRwsQQJ2+yWLas50Atm8H4dTScPG/SGSRJYyIuOV2p/FmmgG93pV4WPO72vUM15wUHgHqzpQzosYhnUxx0DvVGLc2wW53wNcOVwgL6y/5XTape3GkqsJ0bYad5+Z4Jy6i8aKBGoEe9qVFQ3xqd/pHciXDu8sfUQ8VbL4dqazkwwJtDD1P0ir2oMANi7a7Z7dagk/kHIegwqxdmaiQUbJmOHfZLC9FklPCNyaq8AUZZ6vGus7lIoZae0vj2LnVEJbjY7VXqiPcGzCtw58MlqLAJ3DqOTcxt+NotZeAqXLcu2FSRch3dkx9cDtVqgyETO292dqNLc3hQ==
    IBM_ENTITLED_REGISTRY_USER: AgB1oHNGOjyIDBi/v0FDWDEDRQUd1stXXlEKXZh7W3JbI9rlu0KfWrhnk59pnDMLgyrAQOmp194/YBd/J9GhAuvtSyapC9XvYe7g/OlGNT6glhi/uXC/4QKBqkDCB8vgtXwyGKaIZTNsy5DFTkJfVCX6azjWSm9mEylcjE6bV5kXykqjQK5Lbcx6FrR2tT4VZqgtssi2bP2zw46jJT2lCQYyxCnu+PmPXauMPE2KGXPEOBh4zVvBP81gmSWI73NIQCAnMTqIoHOPkqGt1CLsItKu+mQ7dLM80pKsd6+YiqAdRJLbqMjMEqVmsDg5ISZn+2ISM1tkTh1nVaAK0t5MsL45GrfBYlV7dpnCqTvLPP9nhztLXgGtwSix28XobaGoLK+eaNvDHiVzEz1ACG06ueSTKtc3rDHqQez5dkT1DL5rRr2Jh8MGmucwnEiCjgeWNGEhGOx1ZCatMFkwT+jEoAcaRMllr3dQU7fHDqwVbqGzjcTs9+g3FzpRWXW6Jh3ifNUq8GuLRsDmh5mD4a7Cyn04ElgiuOd1LC9aaLJgfbT+CYoha8DyhyYEgb6uB883FMdOEzNIUyJtjDYDjU1+ifyL2kSRsFuchgp1zbE/dlbtFJSdKY8akhAZzN3S483fdTkLlffTk32CL9iZF49UhvwcARkbF47cH51GbmOWuO2TLD1wvK64uDtWusx4TSeoXv+QJA==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci
    type: Opaque

